export const FETCH_USER_REQUEST = "FETCH_USER_REQUEST";
export const FETCH_USER_SUCCESS = "FETCH_USER_SUCCESS";
export const FETCH_USER_FAILURE = "FETCH_USER_FAILURE";

//Authentication Action types
export const AUTH_START = "AUTH_START";
export const AUTH_SUCCESS = "AUTH_SUCCESS";
export const AUTH_FAIL = "AUTH_FAIL";

export const FETCH_DROPDOWN_START = "FETCH_DROPDOWN_START";
export const FETCH_DROPDOWN_SUCCESS = "FETCH_DROPDOWN_SUCCESS";
export const FETCH_DROPDOWN_FAILED = "FETCH_DROPDOWN_FAILED";
export const FETCH_DROPDOWN_CLEAR = "FETCH_DROPDOWN_CLEAR";
